platform :ios, '8.0'
target 'gankme' do
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'YYText'
    pod 'YYCategories'
    pod 'ReactiveObjC'
    pod 'RKDropdownAlert'
    pod 'MKDropdownMenu'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'YTKNetwork'
    pod 'SDWebImage'
    pod 'IQKeyboardManager'
end
